### ISSUE TITLE
Script tags in Chart Atoms

### ISSUE THREAD

**Issue by webb04** [guardian/atoms-rendering#65]
I've been using the atoms in apps-rendering and all the expandable ones are working great. I've had an issue with the chart atom however.

Is there a reason for using `<gu-script>` in the chart atom? Would it be possible to add a prop to be able to use `<script>` tags?

https://github.com/guardian/atoms-rendering/blob/main/src/ChartAtom.tsx#L12

@nitro-marky @shtukas

**Comment by nitro-marky** [comment]
This was something that @gtrufitt and I discovered, in order to get the iFrameMessenger working to resize the atom frontend looks for gu-script and strips them out. I'll have a look at to see if script can be added. Though I might need to check with Gareth when he's back!

**Comment by webb04** [comment]
Great, thanks a lot!
